version: "3"
services:

  app:
    build: .
    image: neetshin/minazuki-bot
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - web
    volumes:
      - .:/minazuki-bot
