version: "3"
services:

  app:
    build:
      context: .
      args:
        - "ssl_certificate="
    image: neetshin/minazuki-bot
    restart: always
    env_file: .env
    ports:
      - "3000:443"
